#!/bin/bash
set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Variables
RELEASE_DIR="/opt/ayan-taraz/releases/$(date +%Y%m%d_%H%M%S)"
ENV_FILE="/opt/ayan-taraz/env/production.env"
CURRENT_LINK="/opt/ayan-taraz/current"

# Ensure directories exist
mkdir -p "$RELEASE_DIR" "/opt/ayan-taraz/env" "/opt/ayan-taraz/uploads"

# Generate production.env from .env (or create default if .env missing)
gen_secret() { openssl rand -base64 32 | tr -d '/+=' | cut -c1-32; }

if [ ! -f "$ENV_FILE" ]; then
  if [ -f "./.env" ]; then
    cp "./.env" "$ENV_FILE"
    echo -e "${GREEN}✓ Copied .env to $ENV_FILE${NC}"
  else
    SERVER_IP="${SERVER_IP:-$(curl -s ifconfig.me || echo 'change_me')}"
    POSTGRES_PASSWORD=$(gen_secret)
    REDIS_PASSWORD=$(gen_secret)
    JWT_SECRET=$(gen_secret)
    JWT_REFRESH_SECRET=$(gen_secret)

    cat > "$ENV_FILE" << EOL
# Auto-generated by bootstrap.sh — edit this file for your deployment
SERVER_IP=${SERVER_IP}
SMS_API_KEY=CHANGE_ME
ADMIN_PHONE=09133374162,09134292329

POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
REDIS_PASSWORD=${REDIS_PASSWORD}
JWT_SECRET=${JWT_SECRET}
JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}

NODE_ENV=production
PORT=3001
TZ=Asia/Tehran
LOG_LEVEL=warn
JWT_EXPIRES_IN=30d

OTP_EXPIRY_SECONDS=300
OTP_MAX_ATTEMPTS=5
OTP_RESEND_LIMIT=3
OTP_RESEND_WINDOW_MINUTES=10
OTP_BLOCK_DURATION_MINUTES=30

RATE_LIMIT_TTL=60000
RATE_LIMIT=100
HEALTH_CHECK_INTERVAL=30000
POSTGRES_USER=ayantaraz
POSTGRES_DB=ayantaraz
EOL
    echo -e "${GREEN}✓ Created $ENV_FILE with auto-generated secrets${NC}"
    echo -e "${YELLOW}⚠ Set SMS_API_KEY in $ENV_FILE for OTP to work${NC}"
  fi
else
  echo -e "${YELLOW}⚠ $ENV_FILE already exists, skipping creation${NC}"
fi

# Copy release files
echo -e "${GREEN}→ Copying release files to $RELEASE_DIR${NC}"
cp -r .env.production docker-compose.yml infra "$RELEASE_DIR/"

# Set permissions
chmod -R 750 "$RELEASE_DIR"
chown -R ayan:ayan "$RELEASE_DIR"

# Create current symlink
ln -sfn "$RELEASE_DIR" "$CURRENT_LINK"
echo -e "${GREEN}✓ Release symlinked to $CURRENT_LINK${NC}"

# Pull images and start services
cd "$RELEASE_DIR"
docker compose pull
docker compose up -d --build

# Health check
echo -e "${GREEN}→ Waiting for services to start...${NC}"
sleep 15

HEALTH_STATUS=$(curl -s http://localhost/health | jq -r '.status' || echo "error")
if [ "$HEALTH_STATUS" = "ok" ]; then
  echo -e "${GREEN}✓ All services are healthy${NC}"
else
  echo -e "${RED}✗ Health check failed: $HEALTH_STATUS${NC}"
  exit 1
fi

# Cleanup old releases (keep last 3)
echo -e "${GREEN}→ Cleaning up old releases${NC}"
ls -dt /opt/ayan-taraz/releases/* | tail -n +4 | xargs rm -rf

echo -e "${GREEN}🚀 Deployment successful!${NC}"